# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"

  config.vm.network "forwarded_port", guest: 55554, host: 55554
  config.vm.network "forwarded_port", guest: 55553, host: 55553
  config.vm.network "forwarded_port", guest: 55552, host: 55552
  config.vm.network "private_network", ip: "192.168.56.3",
    virtualbox__intnet: "cti-platform"
  config.vm.network "public_network", type: "dhcp", bridge: "wlp2s0"
  config.vm.provider "VirtualBox" do |vb|
    vb.gui = true
    vb.memory = "1024"
    vb.cpu = "1"
  end
  config.vm.provision "shell", inline: <<-SHELL, privileged: true
    if netstat -lp | grep "msfrpcd" > /dev/null; then
      echo "Msfrpcd is running."
    else
      msfrpcd -U msf -P metasploit
    fi

    if ! [ -d /usr/share/metasploit-framework/modules/post/windows/purple ]; then
      mkdir /usr/share/metasploit-framework/modules/post/windows/purple &&
      unzip /vagrant/purple.zip -d /usr/share/metasploit-framework/modules/post/windows/purple/ 
    else
      echo "Purple modules exist."
    fi
    SHELL
end
