# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-10"
    config.vm.network "private_network", ip: "192.168.56.2",
      virtualbox__intnet: "cti-platform"
    config.vm.network "public_network", type: "dhcp", bridge: "wlp2s0"
  config.vm.synced_folder "./", "C:\\Users\\vagrant\\vagrant_data"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "2046"
    vb.cpus = "2"
  end
  config.vm.provision "shell", privileged: "true", powershell_elevated_interactive: "true", path: "provision.ps1"
end
