version: '3'

services:
  web:
    build: web
    mem_limit: 1g
    depends_on:
      - db
    container_name: misp_web
    image: misp:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /dev/urandom:/dev/random
      - ${DATA_DIR:-./data}/web:/var/www/MISP
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-misp_db}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-misp}
      - MYSQL_USER=${MYSQL_USER:-misp}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-misp}
      - MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL:-admin@admin.test}
      - MISP_ADMIN_PASSPHRASE=${MISP_ADMIN_PASSPHRASE:-admin}
      - MISP_BASEURL=${MISP_BASEURL:-https://localhost}
      - POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST:-relay.fqdn}
      - TIMEZONE=${TIMEZONE:-UTC}
      - MISP_MODULES_FQDN=http://127.0.0.1:6666
    entrypoint: "wait-for-it.sh -t 0 -h ${MYSQL_HOST:-misp_db} -p 3306 -- /run.sh"

  db:
    container_name: misp_db
    mem_limit: 4g
    image: mysql/mysql-server:5.7
    hostname: ${MYSQL_HOST:-misp_db}
    restart: unless-stopped
    volumes:
      - ${DATA_DIR:-./data}/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-misp}
      - MYSQL_USER=${MYSQL_USER:-misp}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-misp}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-misp}
    ulimits:
      nofile:
        soft: 262144 
        hard: 262144
  
  misp-modules:
    image: dcso/misp-dockerized-misp-modules:latest
    container_name: misp-modules
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-misp}
      - MYSQL_USER=${MYSQL_USER:-misp}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-misp}
    ports:
      - "6666:6666"
    depends_on:
      - db
          #  misp-modules:
          #    image: coolacid/misp-docker:modules-latest
          #    environment:
          #      - MYSQL_DATABASE=${MYSQL_DATABASE:-misp}
          #      - MYSQL_USER=${MYSQL_USER:-misp}
          #      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-misp}
          #      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-misp}
          #    depends_on:
          #      - db
          #    ports:
          #      - "6666:6666"

volumes:
  web:
  db:
