version: '3'
services:
  redis:
    image: redis:5.0.6

  db:
    image: mysql:8.0.19
    mem_limit: 4g
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - "MYSQL_USER=${MYSQL_USER:-misp}"
      - "MYSQL_PASSWORD=${MISP_PASSWORD:-misp}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-misp}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-misp_db}"
    volumes:
      - mysql_data:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE Prevent runaway mysql log
    ulimits:
      nofile:
        soft: 262144 
        hard: 262144
  
  misp:
    image: coolacid/misp-docker:core-latest
    depends_on:
      - redis
      - db
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./server-configs/:/var/www/MISP/app/Config/"
      - "./logs/:/var/www/MISP/app/tmp/logs/"
      - "./files/:/var/www/MISP/app/files"
      - "./ssl/:/etc/nginx/certs"
    environment:
      - "HOSTNAME=${MISP_BASEURL}"
      - "REDIS_FQDN=redis"
      - "INIT=true"             # Initialze MISP, things includes, attempting to import SQL and the Files DIR
      - "CRON_USER_ID=1"        # The MISP user ID to run cron jobs as
      - "MISP_BASEURL=${MISP_BASEURL}"
  misp-modules:
    image: coolacid/misp-docker:modules-latest
    environment:
      - "REDIS_BACKEND=redis"
    depends_on:
      - redis
      - db

volumes:
    mysql_data:
